### ISSUE TITLE
Unable to train with colab

### ISSUE THREAD

**Issue by thangarajdeivasikamani** [CatchZeng/object-detection-api#3]
2 root error(s) found.
  (0) UNIMPLEMENTED:  DNN library is not found.
     [[{{node functional_1/conv1_conv/Conv2D}}]]
     [[StatefulPartitionedCall/SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/MultiClassNonMaxSuppression/Reshape_5/_126]]
  (1) UNIMPLEMENTED:  DNN library is not found.
     [[{{node functional_1/conv1_conv/Conv2D}}]]
0 successful operations.

Pls upload the requirements.txt , Instead of installing from  make file

**Comment by bluecube246** [comment]
I realized when you run the colab code tensor flow updates to 2.9.1. When you look at the colab log on the repo no such behavior is shown and it seems like tensorflow 2.8.0 is used. I did !pip install --upgrade tensorflow==2.8.0 and it's working. But yeah I agree that it would be much more convienient if the versions of the libraries were to be fixed when doing make install. 

By the way updating it to 2.4.1 doesn't work also for some reason. 

But besides that awsome repo.

**Comment by CatchZeng** [comment]
> 

TensorFlow Object Detection API, TensorFlow, Colab, and cudaDNN have been continuously updated and the installation of TensorFlow Object Detection API depends on [setup.py](https://github.com/tensorflow/models/blob/master/research/object_detection/packages/tf2/setup.py) file.

I haven't found a better way to provide the`requirements.txt`. If you have a better way, please submit PR.

**Comment by CatchZeng** [comment]
@thangarajdeivasikamani 

TensorFlow Object Detection API, TensorFlow, Colab, and cudaDNN have been continuously updated and the installation of TensorFlow Object Detection API depends on [setup.py](https://github.com/tensorflow/models/blob/master/research/object_detection/packages/tf2/setup.py) file.

I haven't found a better way to provide the`requirements.txt`. If you have a better way, please submit PR.

**Comment by CatchZeng** [comment]
> I realized when you run the colab code tensor flow updates to 2.9.1. When you look at the colab log on the repo no such behavior is shown and it seems like tensorflow 2.8.0 is used. I did !pip install --upgrade tensorflow==2.8.0 and it's working. But yeah I agree that it would be much more convienient if the versions of the libraries were to be fixed when doing make install.
> 
> By the way updating it to 2.4.1 doesn't work also for some reason.
> 
> But besides that awsome repo.

Great, I have updated on the [commit](https://github.com/CatchZeng/object-detection-api/commit/749e4978d2806484a01cbc8252f5ea326793c450).

**Comment by thangarajdeivasikamani** [comment]
> @thangarajdeivasikamani
> 
> TensorFlow Object Detection API, TensorFlow, Colab, and cudaDNN have been continuously updated and the installation of TensorFlow Object Detection API depends on [setup.py](https://github.com/tensorflow/models/blob/master/research/object_detection/packages/tf2/setup.py) file.
> 
> I haven't found a better way to provide the`requirements.txt`. If you have a better way, please submit PR.

Thanks. I tried with 2.4.1version and working fine. Steps:
1.install the version as mentioned in the repo.
2.Clone the models folder.
3.go to object detection/package/setup.py and remove tensor flow related lines like tensor flow io ,etc.
4. Proceed as same steps.
5. If we get 88 class instead of 80 close error.
6. Uninstall library and add binary file.
Once again thanks for sharing nice detailed pratical notebook.

Regards
D.Thangaraj
